services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: appreservas-app
    container_name: appreservas-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
      - ./.env.docker:/var/www/.env
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: table_reservation
      DB_USERNAME: root
      DB_PASSWORD: root

  db:
    image: mysql:8.0
    container_name: appreservas-db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: table_reservation
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
